import {useCallback,useEffect,useMemo,useState} from "react";
import "./OwnerAnalysisPage.css";
import {analyzeMarket} from "./analysisEngine";
const MARKETS=[["vol10","V10"],["vol10-1s","V10 1s"],["vol25","V25"],["vol25-1s","V25 1s"],["vol50","V50"],["vol50-1s","V50 1s"],["vol75","V75"],["vol75-1s","V75 1s"],["vol100","V100"],["vol100-1s","V100 1s"]];
function apiBase(){const v=String(import.meta.env.VITE_API_URL||"").trim();if(v)return v.replace(/\/$/,"");return location.hostname==="localhost"||location.hostname==="127.0.0.1"?"http://localhost:5000":"";}
function Stat({label,value}){return <div className="ownerAnalysisStat"><div className="ownerAnalysisStatLabel">{label}</div><div className="ownerAnalysisStatValue">{value}</div></div>}
export default function OwnerAnalysisPage(){
 const[marketId,setMarketId]=useState("vol75"),[snapshot,setSnapshot]=useState(null),[error,setError]=useState(""),[loading,setLoading]=useState(true),[updatedAt,setUpdatedAt]=useState(0);
 const analysis=useMemo(()=>snapshot?analyzeMarket(snapshot):null,[snapshot]);
 const loadMarket=useCallback(async()=>{try{setError("");const r=await fetch(`${apiBase()}/api/synthetic/market/${encodeURIComponent(marketId)}?history=600`,{cache:"no-store",credentials:"include",headers:{Accept:"application/json"}});if(!r.ok)throw new Error(`Market feed HTTP ${r.status}`);const p=await r.json();if(!p?.ok||!p?.market)throw new Error(p?.message||"No market snapshot");setSnapshot(p.market);setUpdatedAt(Number(p.serverTime||Date.now()));}catch(e){setError(e?.message||"Unable to load market data")}finally{setLoading(false)}},[marketId]);
 useEffect(()=>{setLoading(true);loadMarket();const t=setInterval(loadMarket,1000);return()=>clearInterval(t)},[loadMarket]);
 return <div className="ownerAnalysisRoot"><div className="ownerAnalysisShell">
  <header className="ownerAnalysisHeader"><div className="ownerAnalysisBrand"><div className="ownerAnalysisLogo">M</div><div><h1 className="ownerAnalysisTitle">MetaBinary Owner Analysis</h1><div className="ownerAnalysisSub">Read-only market statistics and setup scoring</div></div></div><div><div className="ownerAnalysisLive"><span className="ownerAnalysisLiveDot"/>{loading?"CONNECTING":"LIVE"}</div><button className="ownerAnalysisRefresh" onClick={loadMarket}>Refresh</button></div></header>
  <div className="ownerAnalysisMarkets">{MARKETS.map(([id,label])=><button key={id} className={`ownerAnalysisMarketButton ${marketId===id?"active":""}`} onClick={()=>setMarketId(id)}>{label}</button>)}</div>
  {error&&<div className="ownerAnalysisError">{error}</div>}
  <div className="ownerAnalysisGrid">
   <section className="ownerAnalysisCard"><div className="ownerAnalysisCardTitle">{snapshot?.label||marketId}</div><div className="ownerAnalysisPriceRow"><div><div className="ownerAnalysisPrice">{analysis?analysis.currentPrice.toFixed(6):"—"}</div><div className="ownerAnalysisSub">Updated {updatedAt?new Date(updatedAt).toLocaleTimeString():"—"}</div></div><div className="ownerAnalysisDigit">{analysis?.lastDigit??"—"}</div></div><div className="ownerAnalysisDigits">{(analysis?.distribution||Array.from({length:10},(_,digit)=>({digit,percent:0}))).map(x=><div className="ownerAnalysisDigitCell" key={x.digit}><div className="ownerAnalysisDigitNumber">{x.digit}</div><div className="ownerAnalysisDigitPercent">{x.percent.toFixed(1)}%</div></div>)}</div></section>
   <section className="ownerAnalysisCard"><div className="ownerAnalysisCardTitle">Analysis</div><div className="ownerAnalysisStats"><Stat label="Even / Odd" value={analysis?`${analysis.parity.evenPercent.toFixed(1)}% / ${analysis.parity.oddPercent.toFixed(1)}%`:"—"}/><Stat label="Parity bias" value={analysis?.parityBias||"—"}/><Stat label="Over 2" value={analysis?`${analysis.threshold2.overPercent.toFixed(1)}%`:"—"}/><Stat label="Under 2" value={analysis?`${analysis.threshold2.underPercent.toFixed(1)}%`:"—"}/><Stat label="Momentum" value={analysis?.momentum.direction||"—"}/><Stat label="Volatility" value={analysis?.volatility.label||"—"}/><Stat label="Highest digit" value={analysis?.bestDigit?`${analysis.bestDigit.digit} (${analysis.bestDigit.percent.toFixed(1)}%)`:"—"}/><Stat label="Lowest digit" value={analysis?.coldDigit?`${analysis.coldDigit.digit} (${analysis.coldDigit.percent.toFixed(1)}%)`:"—"}/><Stat label="Confidence" value={analysis?`${analysis.confidence.toFixed(0)}% ${analysis.confidenceLabel}`:"—"}/><Stat label="Samples" value={analysis?.sampleSize??"—"}/></div><div className={`ownerAnalysisSetup ${analysis?.setup==="POSSIBLE SETUP"?"ready":""}`}>{analysis?.setup||"WAIT"}</div><div className="ownerAnalysisFootnote">Read-only analysis. It does not alter trade outcomes and cannot guarantee a winning entry.</div></section>
  </div>
 </div></div>
}
